# Generated by Django 3.2.3 on 2021-05-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepala_keluarga', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'keluarga',
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wilayah', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wilayah',
            },
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_anggota', models.CharField(max_length=10, unique=True)),
                ('status_anggota', models.CharField(choices=[('ANGGOTA_SIDI', 'Anggota Sidi'), ('ANGGOTA_ANAK', 'Anggota Anak'), ('SIMPATISAN', 'Simpatisan'), ('NON_AKTIF', 'Non Aktif')], default='ANGGOTA', max_length=20)),
                ('nama_anggota', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('kelurahan', models.CharField(blank=True, max_length=50)),
                ('kecamatan', models.CharField(blank=True, max_length=50)),
                ('kota_kabupaten', models.CharField(blank=True, max_length=50)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('jenis_kelamin', models.CharField(choices=[('LK', 'Laki-Laki'), ('PR', 'Perempuan')], default='LK', max_length=2)),
                ('nomor_hp', models.CharField(blank=True, max_length=30)),
                ('alamat_email', models.EmailField(blank=True, max_length=254)),
                ('status_pernikahan', models.CharField(choices=[('MENIKAH', 'Menikah'), ('BELUM_MENIKAH', 'Belum Menikah'), ('CERAI', 'Cerai')], default='MENIKAH', max_length=15)),
                ('status_kehidupan', models.CharField(choices=[('HIDUP', 'Hidup'), ('ALMARHUM', 'Almarhum')], default='HIDUP', max_length=15)),
                ('lokasi_pemakaman', models.CharField(choices=[('N_SM', 'Bukan Sari Mulia'), ('Y_SM', 'Sari Mulia')], default='N_SM', max_length=5)),
                ('lokasi_sari_mulia', models.CharField(blank=True, max_length=50)),
                ('golongan_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2)),
                ('golongan_darah_rhesus', models.CharField(choices=[('RP', 'Rhesus Positif'), ('RN', 'Rhesus Negatif')], default='RP', max_length=2)),
                ('etnik', models.CharField(choices=[('ACEH', 'Aceh'), ('BALI', 'Bali'), ('BANTEN', 'Banten'), ('BANJAR', 'Banjar'), ('BATAK', 'Batak'), ('BETAWI', 'Betawi'), ('BUGIS', 'Bugis'), ('CIREBON', 'Cirebon'), ('DAYAK', 'Dayak'), ('GORONTALO', 'Gorontalo'), ('JAWA', 'Jawa'), ('LAMPUNG', 'Lampung'), ('MADURA', 'Madura'), ('MAKASAR', 'Makasar'), ('MELAYU', 'Melayu'), ('MINAHASA', 'Minahasa'), ('MINANGKABAU', 'Minangkabau'), ('NIAS', 'Nias'), ('PALEMBANG', 'Palembang'), ('TIONGHOA', 'Tionghoa'), ('SASAK', 'Sasak'), ('SUNDA', 'Sunda')], default='MELAYU', max_length=15)),
                ('pendidikan', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA/SPK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S1', max_length=10)),
                ('pekerjaan', models.CharField(choices=[('PNS', 'PNS'), ('TNI_POLRI', 'TNI/POLRI'), ('KARYAWAN_SWASTA', 'Karyawan Swasta'), ('WIRAUSAHA', 'Wirausaha'), ('PROF_MANDIRI_MEDIS', 'Profesional Mandiri Medis'), ('PROF_MANDIRI_HUKUM', 'Profesional Mandiri Hukum'), ('PROF_MANDIRI_PROYEK', 'Profesional Mandiri Tidak Tetap/Proyek/Konsultan'), ('PENSIUNAN', 'Pensiunan'), ('MAHASISWA', 'Mahasiswa'), ('PELAJAR', 'Pelajar'), ('RUMAH_TANGGA', 'Bapak/Ibu Rumah Tangga'), ('LAINNYA', 'Lainnya')], default='PNS', max_length=30)),
                ('tanggal_nikah', models.DateField(blank=True, null=True)),
                ('gereja_nikah', models.CharField(blank=True, max_length=100)),
                ('pendeta_nikah', models.CharField(blank=True, max_length=100)),
                ('tanggal_baptis', models.DateField(blank=True, null=True)),
                ('gereja_baptis', models.CharField(blank=True, max_length=100)),
                ('pendeta_baptis', models.CharField(blank=True, max_length=100)),
                ('tanggal_sidi', models.DateField(blank=True, null=True)),
                ('gereja_sidi', models.CharField(blank=True, max_length=100)),
                ('pendeta_sidi', models.CharField(blank=True, max_length=100)),
                ('minat_pelayanan', models.CharField(choices=[('PADUAN_SUARA', 'Paduan Suara'), ('PEMUSIK', 'Pemusik'), ('MULTIMEDIA', 'Multimedia'), ('FASILITATOR_PA', 'Fasilitator PA'), ('GURU_SEKOLAH_MINGGU', 'Guru Sekolah Minggu'), ('GURU_TUNAS_REMAJA', 'Guru Tunas Remaja'), ('PEMERHATI', 'Pemerhati'), ('KEDUKAAN', 'Kedukaan'), ('PARENTING', 'Parenting'), ('PASUTRI', 'Pasutri'), ('LEKTOR', 'Lektor'), ('PNJ', 'Pemandu Nyanyian Jemaat'), ('PEMAZMUR', 'Pemazmur'), ('DIAKONIA', 'Diakonia'), ('PEMELIHARA_BANGUNAN', 'Pemelihara Bangunan')], default='PENATUA', max_length=30)),
                ('foto_anggota', models.ImageField(blank=True, upload_to='images/')),
                ('nomor_kartu_parkir', models.CharField(blank=True, max_length=50)),
                ('alasan_non_aktif', models.CharField(choices=[('NONE', 'Tidak Ada Alasan'), ('ATKE', 'Atestasi Keluar'), ('PIKK', 'Pindah Keluar Kota'), ('PIAG', 'Pindah Agama')], default='NONE', max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_keluarga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.keluarga')),
                ('wilayah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.wilayah')),
            ],
            options={
                'db_table': 'anggota',
            },
        ),
    ]
