# Generated by Django 3.2.3 on 2021-05-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kepala_keluarga', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Keluarga',
                'db_table': 'keluarga',
            },
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_anggota', models.CharField(max_length=10, unique=True)),
                ('status_anggota', models.CharField(choices=[('ANGGOTA_SIDI', 'Anggota Sidi'), ('ANGGOTA_ANAK', 'Anggota Anak'), ('SIMPATISAN', 'Simpatisan'), ('NON_AKTIF', 'Non Aktif')], default='ANGGOTA', max_length=30)),
                ('kepala_keluarga', models.BooleanField(default=False)),
                ('nama_anggota', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('kelurahan', models.CharField(blank=True, max_length=50)),
                ('kecamatan', models.CharField(blank=True, max_length=50)),
                ('kota_kabupaten', models.CharField(blank=True, max_length=50)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('jenis_kelamin', models.CharField(choices=[('NN', 'None'), ('LAKILAKI', 'Laki-Laki'), ('PEREMPUAN', 'Perempuan')], default='NN', max_length=15)),
                ('nomor_telp', models.CharField(blank=True, max_length=30)),
                ('nomor_hp', models.CharField(blank=True, max_length=30)),
                ('nomor_darurat', models.CharField(blank=True, max_length=30)),
                ('alamat_email', models.EmailField(blank=True, max_length=254)),
                ('status_pernikahan', models.CharField(choices=[('MENIKAH', 'Menikah'), ('BELUM_MENIKAH', 'Belum Menikah'), ('DUDA_JANDA', 'Duda/Janda')], default='MENIKAH', max_length=15)),
                ('status_kehidupan', models.CharField(choices=[('HIDUP', 'Hidup'), ('ALMARHUM', 'Almarhum')], default='HIDUP', max_length=15)),
                ('lokasi_pemakaman', models.CharField(choices=[('NON_SARIMULIA', 'Bukan Sari Mulia'), ('YES_SARIMULIA', 'Sari Mulia')], default='NON_SARIMULIA', max_length=15)),
                ('lokasi_sari_mulia', models.CharField(blank=True, max_length=50)),
                ('golongan_darah', models.CharField(choices=[('NN', 'None'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='NN', max_length=2)),
                ('golongan_darah_rhesus', models.CharField(choices=[('NN', 'None'), ('RP', 'Rhesus Positif'), ('RN', 'Rhesus Negatif')], default='NN', max_length=2)),
                ('tanggal_nikah', models.DateField(blank=True, null=True)),
                ('gereja_nikah', models.CharField(blank=True, max_length=100)),
                ('pendeta_nikah', models.CharField(blank=True, max_length=100)),
                ('tanggal_baptis', models.DateField(blank=True, null=True)),
                ('gereja_baptis', models.CharField(blank=True, max_length=100)),
                ('pendeta_baptis', models.CharField(blank=True, max_length=100)),
                ('tanggal_sidi', models.DateField(blank=True, null=True)),
                ('gereja_sidi', models.CharField(blank=True, max_length=100)),
                ('pendeta_sidi', models.CharField(blank=True, max_length=100)),
                ('foto_anggota', models.ImageField(blank=True, upload_to='images/')),
                ('nomor_kartu_parkir', models.CharField(blank=True, max_length=50)),
                ('alasan_non_aktif', models.CharField(choices=[('TIDAK_ADA', 'Tidak Ada Alasan'), ('ALMARHUM', 'Almarhum'), ('ATESTASI_KELUAR', 'Atestasi Keluar'), ('PINDAH_KOTA', 'Pindah Keluar Kota'), ('PINDAH_AGAMA', 'Pindah Agama')], default='TIDAK_ADA', max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('riwayat_pelayanan', models.TextField(blank=True)),
                ('gereja_asal', models.CharField(blank=True, max_length=50)),
                ('verifikasi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_support.etnik')),
                ('minat_pelayanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_support.pelayanan')),
                ('nama_kepala_keluarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.keluarga')),
                ('nob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_support.nob')),
                ('pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_support.pendidikan')),
                ('profesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_support.profesi')),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_support.wilayah')),
            ],
            options={
                'verbose_name_plural': 'Anggota',
                'db_table': 'anggota',
            },
        ),
    ]
